Create Code of Conduct
bitfield/script pull request #135
Opened 2022-10-23 02:30 UTC by Schow94

2022-10-23 09:09 UTC, bitfield requested changes
Looks great!

2022-10-23 09:09 UTC, bitfield commented on .github/CODE_OF_CONDUCT.md
> +• Using welcoming and inclusive language
I think these bullets need an indent to be rendered as Markdown bullets—if you preview the file you'll see the list is collapsed into a single paragraph.

2022-10-23 09:09 UTC, bitfield commented on CONTRIBUTING.md
> +As a contributor you can help keep the script community inclusive and open to everyone. Please read and adhere to our [Code of Conduct](CODE_OF_CONDUCT.md).
```suggestion
As a contributor you can help keep the `script` community inclusive and open to everyone. Please read and adhere to our [Code of Conduct](CODE_OF_CONDUCT.md).
```

2022-11-02 16:03 UTC, Schow94 commented on .github/CODE_OF_CONDUCT.md
> +* Using welcoming and inclusive language
Bullets changed to Markdown bullets

2022-11-02 17:16 UTC, bitfield commented
Nice work @Schow94! I have a question: is there a special reason for the Code of Conduct to be in a `.github` subfolder? Does that have some special meaning to GitHub? Otherwise I would probably have put it in the root folder next to the `CONTRIBUTING` guide, for example.

2022-11-16 03:41 UTC, Schow94 commented
I saw that on another project, but I can move it to the project root folder if preferred. I don't see any reason why it needs to be in .github subfolder.

2022-11-16 10:10 UTC, bitfield commented
Yes, I think that'll make it easier to find. [This page](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project) shows it being added to the root folder.

2022-11-16 17:06 UTC, merged

2022-11-16 17:06 UTC, bitfield commented
Nice work @Schow94! Thanks a lot.